server:
  # 设置后端 SpringBoot 端口
  port: 8000
  servlet:
    context-path: /


# 配置数据库连接相关信息
spring:
  application:
    name: service-coupon
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/sanguimall_sms?useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 333
    hikari:
      maximum-pool-size: 30
      minimum-idle: 30
      connection-timeout: 5000
      idle-timeout: 0
      max-lifetime: 18000000

# 配置redis的连接信息
#data:
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    password:
#    database:

# 指定以下mapper.xml文件的位置
mybatis:
  mapper-locations: classpath:mapper/*.xml